// Q8. Develop a program to demonstrate the use of exception handling by using try, catch and finally block inside a class.
#include <iostream>
using namespace std;
int main()
{
    return 0;
}